openapi: 3.0.0
info:
  title: My API
  description: API documentation for my project
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /products:
    get:
      summary: Get all products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                 type: object
                 properties:
                   id:
                     type: string
                     example: 7567ec4b-b10c-45c5-9345-fc73c48a80a1
                   title:
                     type: string
                     example: Skirt
                   description:
                     type: string
                     example: Red skirt for office
                   price:
                     type: integer
                     example: 23

  /products/{id}:
    get:
      summary: Get a product by id
      operationId: getProductsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                      id:
                        type: string
                        example: 7567ec4b-b10c-45c5-9345-fc73c48a80a1
                      title:
                        type: string
                        example: Skirt
                      description:
                        type: string
                        example: Red skirt for office
                      price:
                        type: integer
                        example: 23
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: Product with id 1234 not found